### ISSUE TITLE
Part 3 of MADA Project: Peer Review

### ISSUE THREAD

**Issue by Kamidala** [nicole-luisi/NICOLELUISI-MADA-project#1]
Hi Nicole!

Very nice job; I was definitely wowed by your generated graphics for analysis, haha.

When I first opened your README file in the main project folder, I didn't quite know where to start. Perhaps direct your audience to first look at the README in the `code` subdirectory for processing and analysis procedures or the manuscript for an overall view of the project and its results?

In your processing code file, I came across an error that stopped me from fully running the code: '`Error in match.names(clabs, names(xi)): names don’t match previous names`' for line 114 of code “`allnewdx<-rbind(national_sub_newdx,regional_sub_newdx)`”. I also encountered another error in joinpoint_analysis: "`Error in library(nih.joinpoint): there is no package called ‘nih.joinpoint'`."

I would also advise for you to remove the slides folder in your `products` subdirectory if you don't intend to use them.

Looking forward to seeing how the rest of your project turns out!

Rubric Score: 2

**Comment by nicole-luisi** [comment]
Hi Kailin, thanks for your feedback. I will add some additional information to clarify the steps in the README. The error you are encountering is because I am using a proprietary software that must be installed on the users local machine to work. Dr Handel is aware that this portion will not be reproducible by others and I have notes throughout all of the files to alert the user to this. I did however make sure that all the output from that analysis software was available so all of the other analysis and manuscript code can be run by others.
